fix(installer): add windows package installer

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -48,8 +48,12 @@ install_cue() {
   local download_url
   platform=$(get_platform)
   arch=$(get_arch)
+  ext=".tar.gz"
+  if [ "$platform" == "windows" ]; then
+    ext=".zip"
+  fi
 
-  local source_path="${install_path}/bin/cue.tar.gz"
+  local source_path="${install_path}/bin/cue${ext}"
   local distination="${install_path}/bin"
 
   (
@@ -58,7 +62,15 @@ install_cue() {
     download_file=$(curl -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/cuelang/cue/releases/tags/v${version}" | grep "name" | grep "cue_v${version}\|cue_${version}" | awk '{print $2}' | grep -i "$platform" | grep -i "$arch" | sed -e 's/\"//g' | sed -e 's/,//g')
     download_url="https://github.com/cuelang/cue/releases/download/v${version}/$download_file"
     curl -L "$download_url" >"$source_path" || fail "Could not download $download_url"
-    tar zxvf "$source_path" -C "$distination" >/dev/null || fail "Could not uncompress"
+    case $platform in
+      windows)
+        unzip "$source_path" -d "$distination" || fail "Could not uncompress"
+        ;;
+      *)
+        tar zxvf "$source_path" -C "$distination" >/dev/null || fail "Could not uncompress"
+        ;;
+    esac
+
     rm "$source_path"
     echo "The cue $version installation was successful!"
   ) || (
