fix(file): inconsistent named file issue

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -11,7 +11,7 @@ get_arch() {
   local arch=""
 
   case "$(uname -m)" in
-    x86_64 | amd64) arch="amd64" ;;
+    x86_64 | amd64) arch="amd64\|x86_64" ;;
     aarch64 | arm64) arch="arm64" ;;
     *)
       fail "Arch '$(uname -m)' not supported!"
@@ -49,13 +49,15 @@ install_cue() {
   platform=$(get_platform)
   arch=$(get_arch)
 
-  download_url="https://github.com/cuelang/cue/releases/download/v${version}/cue_v${version}_${platform}_${arch}.tar.gz"
   local source_path="${install_path}/bin/cue.tar.gz"
   local distination="${install_path}/bin"
 
   (
     echo "∗ Downloading and installing cue $version..."
     mkdir -p "$distination"
+    curl -L "https://github.com/cuelang/cue/releases/download/v${version}/checksums.txt" >"${install_path}/bin/checksums.txt" || fail "Could not download v${version}/checksums.txt"
+    download_file=$(grep <"$install_path"/bin/checksums.txt -i "$platform" | grep -i "$arch" | awk '{print $2}')
+    download_url="https://github.com/cuelang/cue/releases/download/v${version}/$download_file"
     curl -L "$download_url" >"$source_path" || fail "Could not download $download_url"
     tar zxvf "$source_path" -C "$distination" >/dev/null || fail "Could not uncompress"
     rm "$source_path"
