Update install script

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -51,7 +51,7 @@ function install_cue() {
     echo "∗ Downloading and installing cue..."
     mkdir -p "$distination"
     curl --silent --location --create-dirs --output "$source_path" "$download_url" || fail "Could not download"
-    tar zxf "$source_path" -C "$distination" --strip-components=1 >/dev/null || fail "Could not uncompress"
+    tar zxf "$source_path" -C "$distination" >/dev/null || fail "Could not uncompress"
     rm "$source_path"
     echo "The installation was successful!"
   ) || (
